name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true  # Add this line

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm install
    
    - name: tests
      run: npm test --ci
    
    - name: Display Test Results
      run: echo "Test results:" && cat test_results.xml 

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test_results2.xml 

    - name: Install Vercel CLI
      run: npm install -g vercel
    
    - name: Deploy to Vercel (using Secret)
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: vercel --prod
